while:
	ghc while.hs

clean:
	rm -f while.hi
	rm -f while.o
	rm -f Arith.hi
	rm -f Arith.o
	rm -f Bool.hi
	rm -f Bool.o
	rm -f ControlStructures.hi
	rm -f ControlStructures.o
	rm -f General.hi
	rm -f General.o

realClean:
	make clean
	rm -f while
